# Setup
title:               David Lipshutz
tagline:             
description:         
url:                 http://davidlipshutz.com
baseurl:             ''
paginate:            5
permalink:     
email:               lipshutz@gmail.com      

include:
  - _pages

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0