# Setup
title:               David Lipshutz
tagline:             
description:         
url:                 http://davidlipshutz.com
baseurl:             ''
paginate:            
permalink:     
email:               lipshutz@gmail.com      

# About/contact
author:
  name:              David Lipshutz
  email:             lipshutz@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0